### ISSUE TITLE
Logo proposal for ANDROID-BIG-DIALER

### ISSUE THREAD

**Issue by ggabogarcia** [joaomantovani/android-big-dialer#15]
Hello, I'm a graphic designer and I like to collaborate with open source projects. I would like to design a logo for your Project I will be happy to collaborate with you :)

**Comment by joaomantovani** [comment]
@ggabogarcia Hi, it would be awesome! I would love the help

**Comment by joaomantovani** [comment]
Hi @ggabogarcia, I published the app in the store with a custom logo. https://play.google.com/store/apps/details?id=com.joaomantovani.androidbigdialer, after your logo, I'll replace

**Comment by ggabogarcia** [comment]
I apologize to you sir for my absence, tomorrow I send the proposals :)

**Comment by joaomantovani** [comment]
No problem, do in your time!

**Comment by ggabogarcia** [comment]
Hello sir :) here is my proposal, look in the play store and many of the icons and logos are similar, most use a phone, use the letter "B" and in the negative space I placed a phone. I gave a different approach to the rest :) I hope you like it. Any change, let me know.

![bigdailer](https://user-images.githubusercontent.com/35750428/42848561-9ffa2cc6-89e5-11e8-9691-73aff2960437.jpg)

**Comment by joaomantovani** [comment]
Wow, it's awesome! Really a gooood job! I'll replace the temporary logo in the store and put you as a contributor. Many thanks!

**Comment by joaomantovani** [comment]
Serious, it's awesome!

**Comment by ggabogarcia** [comment]
That's great sir, this is still a draft, I have to correct some details in the lines :), I'll also send you editable files svg, eps, pdf. Tell me the different sizes in which you need the logo to make them :)

**Comment by joaomantovani** [comment]
To upload the logo, I need this:
Hi-res icon 
512 x 512 px
32-bit PNG (with alpha)

I'll need the SVG icon to put in the Feature Graphic.
(The SVG will fit this)

Thanks in advance!

**Comment by ggabogarcia** [comment]
Hello sir, I already sent you the files. :smile_cat:

**Comment by joaomantovani** [comment]
Thanks man! I'll replace the icon on the playstore and put your name as contributor in github/playstore.

Very nice job! Congratulations

**Comment by ggabogarcia** [comment]
![DERECHOS.jpg](https://cdn.steemitimages.com/DQmVSH7hxt3nuyDxNRdWUBUBtfR11TyvLxM1F1C4vYW5UzG/DERECHOS.jpg)
This work is licensed under a [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/)

**Comment by joaomantovani** [comment]
I changed the README.MD and put you as a "logo design" and linking to your github account. Feel free to change with you want

**Comment by joaomantovani** [comment]
I published your logo/art at playstore, but it's processing right now. I credited you using this text in the app full description:

> CREDITS
>
> - "BigDialer logo" by ggabogarcia is licensed under Creative Commons Attribution 4.0 International License.

Please, let me know if I did anything wrong.

Again, you did an awesome job and thank you very much!

**Comment by ggabogarcia** [comment]
Take a look at the store and maybe the icon with white background will work better

**Comment by ggabogarcia** [comment]
I have already updated the files in G-DRIVE

**Comment by ggabogarcia** [comment]
What do you thinks?

![sin titulo-1](https://user-images.githubusercontent.com/35750428/42921991-5084fc2a-8ae4-11e8-829a-4928724661db.png)

**Comment by joaomantovani** [comment]
I agree. I've made the changes on the playstore, just waiting for the processing

**Comment by ggabogarcia** [comment]
Looks great :100:  :1st_place_medal:

**Comment by joaomantovani** [comment]
Thank you very much, I'm closing this issue. Good luck with your projects. You did an awesome job.
